#Campeões de Dados
## Game - Lol
- Fernando Guilherme
- Gustavo Duarte
- Alana Salvatori
- Luísa Marques
- Thales Conci

# O que apresentar

> O que é o conceito<br>
> Sintaxe básica<br>
> Exemplo simples funcionando<br>
> Erro comum e ou cuidados

### Assunto: **Tratamento de Dados**

> Dados Duplicado<br>
> Valores Faltantes<br>
> Padronização e Conversão de Dados

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dados = {
    "id_inscricao": [
        1, 2, 3, 4, 5, 5, 6, 7, 8, 9,
        10, 11, 12, 13, 14, 15, 16, 17
    ],

    "nome": [
        " lucas silva ",
        "JOAO SOUZA",
        "Mariana Costa",
        None,
        "pedro santos",
        "pedro santos",
        "  ANA LIMA",
        "Carlos Oliveira ",
        "GABRIEL ALVES",
        "fernanda rocha",
        " Rafael Mendes ",
        "beatriz martins",
        "THIAGO SANTOS",
        " julia ferreira ",
        "Bruno Costa",
        "brunoo costa",
        "",
        "   "
    ],

    "idade": [
        21,
        17,
        25,
        None,
        "19",
        "19",
        150,
        22,
        "vinte e três",
        -5,
        21,
        None,
        24,
        18,
        200,
        "20 anos",
        "",
        23
    ],

    "email": [
        "lucas@email.com",
        "JOAO@EMAIL.COM",
        " mariana@email.com ",
        None,
        "pedro@email.com",
        "pedro@email.com",
        "ana@email",
        "carlos@email.com ",
        " gabriel@email.com",
        "fernanda@email",
        "rafaelemail.com",
        "beatriz@@email.com",
        "thiago @email.com",
        "julia@email.c",
        "bruno@email,com",
        "brunooemail.com",
        "",
        "player@@gmail..com"
    ],

    "personagem_preferido": [
      " Ahri ",
      "YASUO",
      "Lux",
      None,
      "Jinx",
      "Jinx",
      "Lee Sin",
      "THRESH",
      "Morgana",
      "Yonee",
      "Zed",
      " Ahri",
      "Katarina",
      "Jinx",
      "Yasuo",
      "Yasuo",
      "",
      "Ahrri"
  ],

    "cpf": [
        "123.456.789-01",
        "98765432100",
        " 111.222.333-44 ",
        None,
        "555.666.777-88",
        "555.666.777-88",
        " 222.333.444-55 ",
        "333.444.555-66",
        "44444444477",
        "555.666.777-8",
        "666.777.888-99",
        "777.888.999-00",
        "888.999.000-11",
        "999.000.111-22",
        "123.456.789-0",
        "ABC.456.789-01",
        "",
        "123.456.789-01"
    ],

    "nickname": [
        " Luquinhas ",
        "JOAOZINHO",
        "Mari",
        None,
        "pedrin",
        "pedrin",
        "ANINHA",
        " c4rlos",
        "GABRIEL",
        "Feh ",
        "RAFA",
        "bia",
        "Thiago",
        "JULIAF",
        "Brunao",
        "brunao",
        "",
        "player23"
    ],

    "elo": [
        "platina",
        "OURO",
        "Diamante",
        None,
        "mestre",
        "mestre",
        "Grandmaster",
        "esmeralda",
        "DIAMNTE",
        "ferro",
        " Ouro ",
        "diamante",
        "MESTRE",
        "Challenger",
        "Lendario",
        "ouroo",
        "",
        None
    ],

    "main_role": [
        "mid",
        "ADC",
        "Support",
        "JUNGLE",
        "top",
        "top",
        "MID",
        "adc",
        "SUPORT",
        "jungle",
        " mid ",
        "TOP",
        "suporte",
        "MID",
        None,
        "AD C",
        "",
        "jungler"
    ],

    "valor_inscricao": [
        50.00,
        50.00,
        50.00,
        None,
        "50",
        "50",
        50.00,
        50,
        50.00,
        -50.00,
        50.00,
        None,
        "cinquenta",
        50.00,
        5000.00,
        0,
        "",
        50.00
    ],

    "status_pagamento": [
        "Pago",
        "PAGO",
        "pago",
        None,
        "Pendente",
        "Pendente",
        " pago ",
        "Pago",
        "PAGOO",
        "Pendente",
        "Pago",
        "pendente",
        "PAGO",
        "Pago",
        "Pago",
        "Nao Pago",
        "",
        None
    ]
}

# Criando o DataFrame, removendo duplicados e isolando na memória
df = pd.DataFrame(dados).drop_duplicates().copy()
df

,id_inscricao,nome,idade,email,personagem_preferido,cpf,nickname,elo,main_role,valor_inscricao,status_pagamento
0,1,lucas silva,21,lucas@email.com,Ahri,123.456.789-01,Luquinhas,platina,mid,50.0,Pago
1,2,JOAO SOUZA,17,JOAO@EMAIL.COM,YASUO,98765432100,JOAOZINHO,OURO,ADC,50.0,PAGO
2,3,Mariana Costa,25,mariana@email.com,Lux,111.222.333-44,Mari,Diamante,Support,50.0,pago
3,4,None,None,None,None,None,None,None,JUNGLE,None,None
4,5,pedro santos,19,pedro@email.com,Jinx,555.666.777-88,pedrin,mestre,top,50,Pendente
6,6,ANA LIMA,150,ana@email,Lee Sin,222.333.444-55,ANINHA,Grandmaster,MID,50.0,pago
7,7,Carlos Oliveira,22,carlos@email.com,THRESH,333.444.555-66,c4rlos,esmeralda,adc,50,Pago
8,8,GABRIEL ALVES,vinte e três,gabriel@email.com,Morgana,44444444477,GABRIEL,DIAMNTE,SUPORT,50.0,PAGOO
9,9,fernanda rocha,-5,fernanda@email,Yonee,555.666.777-8,Feh,ferro,jungle,-50.0,Pendente
10,10,Rafael Mendes,21,rafaelemail.com,Zed,666.777.888-99,RAFA,Ouro,mid,50.0,Pago
11,11,beatriz martins,None,beatriz@@email.com,Ahri,777.888.999-00,bia,diamante,TOP,None,pendente
12,12,THIAGO SANTOS,24,thiago @email.com,Katarina,888.999.000-11,Thiago,MESTRE,suporte,cinquenta,PAGO
13,13,julia ferreira,18,julia@email.c,Jinx,999.000.111-22,JULIAF,Challenger,MID,50.0,Pago
14,14,Bruno Costa,200,"bruno@email,com",Yasuo,123.456.789-0,Brunao,Lendario,None,5000.0,Pago
15,15,brunoo costa,20 anos,brunooemail.com,Yasuo,ABC.456.789-01,brunao,ouroo,AD C,0,Nao Pago
16,16,,,,,,,,,,
17,17,,23,player@@gmail..com,Ahrri,123.456.789-01,player23,None,jungler,50.0,None

In [ ]:
# Cria arquivo excel da tabela
#df.to_excel("inscricoes_lol.xlsx", index=False)

## Passo 1: **Observar a descrição dos dados**

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17 entries, 0 to 17
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id_inscricao          17 non-null     int64
 1   nome                  16 non-null     object
 2   idade                 15 non-null     object
 3   email                 16 non-null     object
 4   personagem_preferido  16 non-null     object
 5   cpf                   16 non-null     object
 6   nickname              16 non-null     object
 7   elo                   15 non-null     object
 8   main_role             16 non-null     object
 9   valor_inscricao       15 non-null     object
 10  status_pagamento      15 non-null     object
dtypes: int64(1), object(10)
memory usage: 1.6+ KB

In [ ]:
nulos = df.isnull().sum().rename("Quantidade de Nulos").reset_index().sort_values(by="Quantidade de Nulos", ascending=False)
nulos.columns = ["Coluna", "Quantidade de Nulos"]
nulos

                  Coluna  Quantidade de Nulos
2                  idade                    2
10      status_pagamento                    2
9        valor_inscricao                    2
7                    elo                    2
1                   nome                    1
6               nickname                    1
3                  email                    1
4   personagem_preferido                    1
5                    cpf                    1
8              main_role                    1
0           id_inscricao                    0

In [ ]:
duplicados = df.duplicated().sum()
print(f"Quantidade de linhas duplicadas: {duplicados}")

Quantidade de linhas duplicadas: 0

In [ ]:
# Linhas duplicadas
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [id_inscricao, nome, idade, email, personagem_preferido, cpf, nickname, elo, main_role, valor_inscricao, status_pagamento]
Index: []

In [ ]:
# Removendo linhas duplicadas
df = df.drop_duplicates()

## Passo 2: **Verificação das colunas**

### **2.1 Tratamento da coluna status_pagamento**

In [ ]:
# Deixar todos os valores com a primeira letra em maiúscula e sem espaços desnecessários
df["status_pagamento"] = df["status_pagamento"].str.strip().str.lower()

In [ ]:
# Valores únicos na coluna status_pagamento
status = df['status_pagamento'].unique()
print(status)

['pago' None 'pendente' 'pagoo' 'nao pago' '']

In [ ]:
# Padronização dos valores, para infomações diferentes
padronizacao_pagamento = {
    "pagou": "Pago",
    "sim": "Pago",
    "yes": "Pago",
    "quitado": "Pago",
    "pagoo": "Pago",

    "nao pago": "Não Pago",
    "não pago": "Não Pago",
    "nao pagou": "Não Pago",
    "não pagou": "Não Pago",
    "nao": "Não Pago",
    "não": "Não Pago",
    "no": "Não Pago",
    "pendente": "Não Pago"
}

# Modificando valores para deixá-los padronizados
df["status_pagamento"] = df["status_pagamento"].replace(padronizacao_pagamento).str.title()

# Novos valores únicos na coluna
print(df['status_pagamento'].unique())

['Pago' None 'Não Pago' '']

In [ ]:
# Valores nulos serão substituidos por verificar
df["status_pagamento"] = df["status_pagamento"].fillna("Verificar")

In [ ]:
# Removendo valores ausentes
df = df[
    (df["status_pagamento"] != "") &
    (df["status_pagamento"].notna())
]

# Novos valores únicos na coluna
print(df['status_pagamento'].unique())

['Pago' 'Verificar' 'Não Pago']

### **2.2 Tratamento da coluna nome**

In [ ]:
# Função title() deixa a primeira letra de cada palavra em maiúscula e o resto em minúscula
# Função strip() para remover espaços antes da primeira palavra e depois da última palavra
df['nome'] = df['nome'].str.title().str.strip()

df = df[df["nome"].notna() & (df["nome"] != "") | (df['status_pagamento'] == 'Pago') & (df['email'] != "")]

df.head()

,id_inscricao,nome,idade,email,personagem_preferido,cpf,nickname,elo,main_role,valor_inscricao,status_pagamento
0,1,Lucas Silva,21,lucas@email.com,Ahri,123.456.789-01,Luquinhas,platina,mid,50.0,Pago
1,2,Joao Souza,17,JOAO@EMAIL.COM,YASUO,98765432100,JOAOZINHO,OURO,ADC,50.0,Pago
2,3,Mariana Costa,25,mariana@email.com,Lux,111.222.333-44,Mari,Diamante,Support,50.0,Pago
4,5,Pedro Santos,19,pedro@email.com,Jinx,555.666.777-88,pedrin,mestre,top,50,Não Pago
6,6,Ana Lima,150,ana@email,Lee Sin,222.333.444-55,ANINHA,Grandmaster,MID,50.0,Pago

### **2.3 Tratamento da coluna idade**

In [ ]:
# Números padronizados
numeros = {
    "vinte": 20,
    "vinte e um": 21,
    "vinte e dois": 22,
    "vinte e três": 23,
    "vinte e quatro": 24,
    "vinte e cinco": 25,
    "vinte e seis": 26,
    "vinte e sete": 27,
    "vinte e oito": 28,
    "vinte e nove": 29,
    "trinta": 30,
}


def padronizar_idade(valor):

    # 1. Valores nulos ou vazios
    if pd.isna(valor):
        return "Não informado"

    valor = str(valor).lower().strip()

    if valor == "":
        return "Não informado"

    # 2. Remove "anos"
    valor = valor.replace("anos", "").strip()

    # 3. Verifica se é número inteiro
    try:
        idade = int(valor)
    except ValueError:

        # 4. Procura número por extenso
        if valor in numeros:
            idade = numeros[valor]
        else:
            return "Não informado"

    # 5. Verifica se a idade está dentro de um intervalo válido
    if idade < 0 or idade > 80:
        return "Não informado"

    return idade

In [ ]:
# Aplicando a função de tratamento da coluna idade
df["idade"] = df["idade"].apply(padronizar_idade)

In [ ]:
df['idade']

0                21
1                17
2                25
4                19
6     Não informado
7                22
8                23
9     Não informado
10               21
11    Não informado
12               24
13               18
14    Não informado
15               20
Name: idade, dtype: object

### **2.4 Tratamento da coluna Elo**

In [ ]:
# Valores únicos da coluna main_role
print("Valores únicos da coluna main_role:")
print(df["main_role"].unique(),"\n")

Valores únicos da coluna main_role:
['mid' 'ADC' 'Support' 'top' 'MID' 'adc' 'SUPORT' 'jungle' ' mid ' 'TOP'
 'suporte' None 'AD C']

In [ ]:
# Padronizar valores da coluna para minúsculas
df["main_role"] = df["main_role"].str.lower()

# Remover os espaços
df["main_role"] = df["main_role"].str.strip()

In [ ]:
# Criar uma lista com os valores permitidos
roles = [
    "top",
    "jungle",
    "mid",
    "adc",
    "support"
]

# Verificar os valores diferentes dos que são permitidos na coluna
print("Valores diferentes dos que são permitidos na coluna:")
print(df['main_role'][df["main_role"].isin(roles) == False].values)

Valores diferentes dos que são permitidos na coluna:
['suport' 'suporte' None 'ad c']

In [ ]:
# Dicionários de valores padronizados
padronizacao_role = {
    # Top
    "top": "top",
    "topo": "top",
    "top lane": "top",
    "toplane": "top",
    "top laner": "top",
    "toplaner": "top",

    # Jungle
    "jungle": "jungle",
    "jg": "jungle",
    "jungler": "jungle",
    "selva": "jungle",
    "floresta": "jungle",

    # Mid
    "mid": "mid",
    "middle": "mid",
    "mid lane": "mid",
    "midlane": "mid",
    "mid laner": "mid",
    "midlaner": "mid",
    "meio": "mid",

    # ADC
    "adc": "adc",
    "ad carry": "adc",
    "adcarry": "adc",
    "bot": "adc",
    "bot lane": "adc",
    "botlane": "adc",
    "bottom": "adc",
    "bottom lane": "adc",
    "atirador": "adc",

    # Support
    "support": "support",
    "sup": "support",
    "suporte": "support",
    "suport": "support",
    "supporter": "support"
}

# Modificando todos os valores diferentes da padronização
df["main_role"] = (
    df["main_role"]
    .str.strip()
    .str.lower()
    .replace(padronizacao_role)
)

# Verificar os valores diferentes dos que são permitidos na coluna
print("Valores diferentes dos que são permitidos na coluna:")
print(df['main_role'][df["main_role"].isin(roles) == False].values)

Valores diferentes dos que são permitidos na coluna:
[None 'ad c']

In [ ]:
# Linhas com valores nulos ou diferentes na coluna main_role
df[~df['main_role'].isin(roles)]

# Deixando no DataFrame com apenas os valores permitidos na coluna main_role
df = df[df['main_role'].isin(roles)]

In [ ]:
# Verificando os valores novo na coluna main_role
uni = df['main_role'].unique()
print(uni)

['mid' 'adc' 'support' 'top' 'jungle']

### **2.5 Tratamento da coluna email**

In [ ]:
def padronizar_email(email):

    # Valores ausentes
    if pd.isna(email) or str(email).strip() == "":
        return "Não informado"

    # Converte para texto, remove espaços e coloca em minúsculo
    email = str(email).strip().lower().replace(" ", "")

    # Se houver mais de um @, mantém apenas o primeiro
    if email.count("@") > 1:
        usuario = email.split("@")[0]
        return usuario + "@email.com"

    # Se não existir @
    if "@" not in email:
        # Tenta separar "rafaelemail.com" → "rafael"
        if "email.com" in email:
            usuario = email.split("email.com")[0]
            return usuario + "@email.com"

        # Caso contrário, considera inválido
        return "Email inválido"

    # Pega somente a parte antes do @
    usuario = email.split("@")[0]

    if usuario == "":
        return "Email inválido"

    # Padroniza o domínio
    return usuario + "@email.com"

In [ ]:
# Aplicando a função de tratamento de email
df["email"] = df["email"].apply(padronizar_email)
df

,id_inscricao,nome,idade,email,personagem_preferido,cpf,nickname,elo,main_role,valor_inscricao,status_pagamento
0,1,Lucas Silva,21,lucas@email.com,Ahri,123.456.789-01,Luquinhas,platina,mid,50.0,Pago
1,2,Joao Souza,17,joao@email.com,YASUO,98765432100,JOAOZINHO,OURO,adc,50.0,Pago
2,3,Mariana Costa,25,mariana@email.com,Lux,111.222.333-44,Mari,Diamante,support,50.0,Pago
4,5,Pedro Santos,19,pedro@email.com,Jinx,555.666.777-88,pedrin,mestre,top,50,Não Pago
6,6,Ana Lima,Não informado,ana@email.com,Lee Sin,222.333.444-55,ANINHA,Grandmaster,mid,50.0,Pago
7,7,Carlos Oliveira,22,carlos@email.com,THRESH,333.444.555-66,c4rlos,esmeralda,adc,50,Pago
8,8,Gabriel Alves,23,gabriel@email.com,Morgana,44444444477,GABRIEL,DIAMNTE,support,50.0,Pago
9,9,Fernanda Rocha,Não informado,fernanda@email.com,Yonee,555.666.777-8,Feh,ferro,jungle,-50.0,Não Pago
10,10,Rafael Mendes,21,rafael@email.com,Zed,666.777.888-99,RAFA,Ouro,mid,50.0,Pago
11,11,Beatriz Martins,Não informado,beatriz@email.com,Ahri,777.888.999-00,bia,diamante,top,None,Não Pago
12,12,Thiago Santos,24,thiago@email.com,Katarina,888.999.000-11,Thiago,MESTRE,support,cinquenta,Pago
13,13,Julia Ferreira,18,julia@email.com,Jinx,999.000.111-22,JULIAF,Challenger,mid,50.0,Pago

### **2.6 Tratamento da coluna personagem favorito**

In [ ]:
# Deixar o texto todo em minúscula
df['personagem_preferido'] = df['personagem_preferido'].str.lower()

# Remover os espaços
df['personagem_preferido'] = df['personagem_preferido'].str.strip()

In [ ]:
correcoes = {
    "yonee": "yone",
    "ahrri": "ahri"
}

df["personagem_preferido"] = df["personagem_preferido"].replace(correcoes).str.title()

In [ ]:
df

,id_inscricao,nome,idade,email,personagem_preferido,cpf,nickname,elo,main_role,valor_inscricao,status_pagamento
0,1,Lucas Silva,21,lucas@email.com,Ahri,123.456.789-01,Luquinhas,platina,mid,50.0,Pago
1,2,Joao Souza,17,joao@email.com,Yasuo,98765432100,JOAOZINHO,OURO,adc,50.0,Pago
2,3,Mariana Costa,25,mariana@email.com,Lux,111.222.333-44,Mari,Diamante,support,50.0,Pago
4,5,Pedro Santos,19,pedro@email.com,Jinx,555.666.777-88,pedrin,mestre,top,50,Não Pago
6,6,Ana Lima,Não informado,ana@email.com,Lee Sin,222.333.444-55,ANINHA,Grandmaster,mid,50.0,Pago
7,7,Carlos Oliveira,22,carlos@email.com,Thresh,333.444.555-66,c4rlos,esmeralda,adc,50,Pago
8,8,Gabriel Alves,23,gabriel@email.com,Morgana,44444444477,GABRIEL,DIAMNTE,support,50.0,Pago
9,9,Fernanda Rocha,Não informado,fernanda@email.com,Yone,555.666.777-8,Feh,ferro,jungle,-50.0,Não Pago
10,10,Rafael Mendes,21,rafael@email.com,Zed,666.777.888-99,RAFA,Ouro,mid,50.0,Pago
11,11,Beatriz Martins,Não informado,beatriz@email.com,Ahri,777.888.999-00,bia,diamante,top,None,Não Pago
12,12,Thiago Santos,24,thiago@email.com,Katarina,888.999.000-11,Thiago,MESTRE,support,cinquenta,Pago
13,13,Julia Ferreira,18,julia@email.com,Jinx,999.000.111-22,JULIAF,Challenger,mid,50.0,Pago

### **2.7 Tratamento da coluna CPF**

In [ ]:
def padronizar_cpf(cpf):

    # Valores ausentes ou vazios
    if pd.isna(cpf) or str(cpf).strip() == "":
        return "Não informado"

    # Converte para texto e remove espaços
    cpf = str(cpf).strip()

    # Remove pontos e hífen
    cpf = cpf.replace(".", "").replace("-", "").replace(" ", "")

    # Verifica se possui somente números
    if not cpf.isdigit():
        return "CPF inválido"

    # Verifica se possui exatamente 11 números
    if len(cpf) != 11:
        return "CPF inválido"

    # Formata o CPF: 000.000.000-00
    return f"{cpf[:3]}.{cpf[3:6]}.{cpf[6:9]}-{cpf[9:]}"

# Aplicando a função de tratamento do CPF
df["cpf"] = df["cpf"].apply(padronizar_cpf)

# Verificando os valores da coluna CPF
df["cpf"]

0     123.456.789-01
1     987.654.321-00
2     111.222.333-44
4     555.666.777-88
6     222.333.444-55
7     333.444.555-66
8     444.444.444-77
9       CPF inválido
10    666.777.888-99
11    777.888.999-00
12    888.999.000-11
13    999.000.111-22
Name: cpf, dtype: object

In [ ]:
df

,id_inscricao,nome,idade,email,personagem_preferido,cpf,nickname,elo,main_role,valor_inscricao,status_pagamento
0,1,Lucas Silva,21,lucas@email.com,Ahri,123.456.789-01,Luquinhas,platina,mid,50.0,Pago
1,2,Joao Souza,17,joao@email.com,Yasuo,987.654.321-00,JOAOZINHO,OURO,adc,50.0,Pago
2,3,Mariana Costa,25,mariana@email.com,Lux,111.222.333-44,Mari,Diamante,support,50.0,Pago
4,5,Pedro Santos,19,pedro@email.com,Jinx,555.666.777-88,pedrin,mestre,top,50,Não Pago
6,6,Ana Lima,Não informado,ana@email.com,Lee Sin,222.333.444-55,ANINHA,Grandmaster,mid,50.0,Pago
7,7,Carlos Oliveira,22,carlos@email.com,Thresh,333.444.555-66,c4rlos,esmeralda,adc,50,Pago
8,8,Gabriel Alves,23,gabriel@email.com,Morgana,444.444.444-77,GABRIEL,DIAMNTE,support,50.0,Pago
9,9,Fernanda Rocha,Não informado,fernanda@email.com,Yone,CPF inválido,Feh,ferro,jungle,-50.0,Não Pago
10,10,Rafael Mendes,21,rafael@email.com,Zed,666.777.888-99,RAFA,Ouro,mid,50.0,Pago
11,11,Beatriz Martins,Não informado,beatriz@email.com,Ahri,777.888.999-00,bia,diamante,top,None,Não Pago
12,12,Thiago Santos,24,thiago@email.com,Katarina,888.999.000-11,Thiago,MESTRE,support,cinquenta,Pago
13,13,Julia Ferreira,18,julia@email.com,Jinx,999.000.111-22,JULIAF,Challenger,mid,50.0,Pago

### **2.8 Tratamento da coluna Elo**

In [ ]:
# Valores únicos da coluna elo
print("Valores únicos da coluna elo:")
print(df["elo"].unique())

# Padronizar os valores para minúsculas
df["elo"] = df["elo"].str.lower().str.strip()

# Dicionário para corrigir os valores
padronizacao_elo = {
    "ferro": "Ferro",
    "bronze": "Bronze",
    "prata": "Prata",
    "ouro": "Ouro",
    "ouroo": "Ouro",
    "platina": "Platina",
    "esmeralda": "Esmeralda",
    "diamante": "Diamante",
    "diamnte": "Diamante",
    "mestre": "Mestre",
    "grandmaster": "Grão-Mestre",
    "grão-mestre": "Grão-Mestre",
    "challenger": "Desafiante",
    "desafiante": "Desafiante",
    "lendario": "Lendário"
}

# Aplicando a padronização
df["elo"] = df["elo"].replace(padronizacao_elo)

# Valores nulos serão substituídos por "Não informado"
df["elo"] = df["elo"].fillna("Não informado")

# Removendo valores vazios
df = df[df["elo"] != ""]

# Verificando os novos valores
print("Valores padronizados da coluna elo:")
print(df["elo"].unique())

Valores únicos da coluna elo:
['platina' 'OURO' 'Diamante' 'mestre' 'Grandmaster' 'esmeralda' 'DIAMNTE'
 'ferro' ' Ouro ' 'diamante' 'MESTRE' 'Challenger']
Valores padronizados da coluna elo:
['Platina' 'Ouro' 'Diamante' 'Mestre' 'Grão-Mestre' 'Esmeralda' 'Ferro'
 'Desafiante']

### **2.9 valor_inscricao**

In [ ]:
def padronizar_valor(valor):
    # 1. Se for nulo ou vazio, assume o valor padrão de 50.0
    if pd.isna(valor) or str(valor).strip() == "":
        return 50.0

    valor_str = str(valor).lower().strip()

    # 2. Corrige o texto por extenso
    if "cinquenta" in valor_str:
        return 50.0

    try:
        num = float(valor_str)
        # 3. Se for negativo (ex: -50.0), transforma em positivo. Se for zero, assume 50.0
        return abs(num) if num != 0 else 50.0
    except ValueError:
        return 50.0

# Aplicando a função na coluna
df["valor_inscricao"] = df["valor_inscricao"].apply(padronizar_valor)

# Exibe o DataFrame final totalmente limpo
df

,id_inscricao,nome,idade,email,personagem_preferido,cpf,nickname,elo,main_role,valor_inscricao,status_pagamento
0,1,Lucas Silva,21,lucas@email.com,Ahri,123.456.789-01,Luquinhas,Platina,mid,50.0,Pago
1,2,Joao Souza,17,joao@email.com,Yasuo,987.654.321-00,JOAOZINHO,Ouro,adc,50.0,Pago
2,3,Mariana Costa,25,mariana@email.com,Lux,111.222.333-44,Mari,Diamante,support,50.0,Pago
4,5,Pedro Santos,19,pedro@email.com,Jinx,555.666.777-88,pedrin,Mestre,top,50.0,Não Pago
6,6,Ana Lima,Não informado,ana@email.com,Lee Sin,222.333.444-55,ANINHA,Grão-Mestre,mid,50.0,Pago
7,7,Carlos Oliveira,22,carlos@email.com,Thresh,333.444.555-66,c4rlos,Esmeralda,adc,50.0,Pago
8,8,Gabriel Alves,23,gabriel@email.com,Morgana,444.444.444-77,GABRIEL,Diamante,support,50.0,Pago
9,9,Fernanda Rocha,Não informado,fernanda@email.com,Yone,CPF inválido,Feh,Ferro,jungle,50.0,Não Pago
10,10,Rafael Mendes,21,rafael@email.com,Zed,666.777.888-99,RAFA,Ouro,mid,50.0,Pago
11,11,Beatriz Martins,Não informado,beatriz@email.com,Ahri,777.888.999-00,bia,Diamante,top,50.0,Não Pago
12,12,Thiago Santos,24,thiago@email.com,Katarina,888.999.000-11,Thiago,Mestre,support,50.0,Pago
13,13,Julia Ferreira,18,julia@email.com,Jinx,999.000.111-22,JULIAF,Desafiante,mid,50.0,Pago